import { describe, expect, it } from 'vitest';
import { DICTIONARIES } from '@/lib/i18n/dictionaries';
import {
  BODY_MOTION,
  HINT_GLYPHS,
  hintLine,
  inkTiming,
  penTimings,
  scheduleLine,
  TITLE_MOTION,
} from './hint-glyphs';

const CONTOUR = /^M-?\d+ -?\d+(?:[LQC]-?\d+ -?\d+(?: -?\d+ -?\d+)*)+Z$/;

describe('hint glyph outlines (generated by `pnpm hint:glyphs`)', () => {
  it('cover the canvas hint copy of every language', () => {
    for (const [locale, dictionary] of Object.entries(DICTIONARIES)) {
      for (const text of [dictionary.canvas.hintTitle, dictionary.canvas.hintBody]) {
        expect(hintLine(text), `${locale}: "${text}" — run \`pnpm hint:glyphs\``).not.toBeNull();
      }
    }
  });

  it('return null for copy that has no outlines yet', () => {
    expect(hintLine('not a hint')).toBeNull();
  });

  it('are laid out left to right on a 1000-unit em', () => {
    expect(HINT_GLYPHS.unitsPerEm).toBe(1000);
    expect(HINT_GLYPHS.ascent).toBeGreaterThan(0);
    expect(HINT_GLYPHS.descent).toBeLessThan(0);
    for (const line of Object.values(HINT_GLYPHS.lines)) {
      expect(line.width).toBeGreaterThan(0);
      expect(line.glyphs.length).toBeGreaterThan(0);
      let previous = -1;
      for (const glyph of line.glyphs) {
        expect(glyph.x).toBeGreaterThanOrEqual(previous);
        expect(glyph.x).toBeLessThan(line.width);
        previous = glyph.x;
      }
    }
  });

  it('reference closed SVG contours only', () => {
    const referenced = new Set(
      Object.values(HINT_GLYPHS.lines).flatMap((line) => line.glyphs.map((glyph) => glyph.g)),
    );
    expect(referenced.size).toBeGreaterThan(0);
    for (const key of referenced) {
      const contours = HINT_GLYPHS.glyphs[key];
      expect(contours, key).toBeDefined();
      expect(contours?.length, key).toBeGreaterThan(0);
      for (const contour of contours ?? []) expect(contour, key).toMatch(CONTOUR);
    }
    expect(Object.keys(HINT_GLYPHS.glyphs).sort()).toEqual([...referenced].sort());
  });

  it('credit the open fonts the outlines were traced from', () => {
    const fonts = Object.values(HINT_GLYPHS.fonts);
    expect(fonts.map((font) => font.name).sort()).toEqual(['Excalifont', 'Xiaolai']);
    for (const font of fonts) {
      expect(font.license).toBe('OFL-1.1');
      expect(font.source).toMatch(/^https:\/\//);
    }
  });
});

describe('scheduleLine', () => {
  it('fits the stagger so a line takes about the profile total', () => {
    expect(scheduleLine(9, TITLE_MOTION)).toEqual({ stagger: 148, duration: 1604 });
  });

  it('clamps the stagger for very short and very long lines', () => {
    expect(scheduleLine(2, TITLE_MOTION).stagger).toBe(TITLE_MOTION.maxStagger);
    expect(scheduleLine(100, BODY_MOTION)).toEqual({
      stagger: BODY_MOTION.minStagger,
      duration: 99 * BODY_MOTION.minStagger + BODY_MOTION.draw,
    });
  });

  it('handles single glyphs and empty lines', () => {
    expect(scheduleLine(1, BODY_MOTION)).toEqual({ stagger: 0, duration: BODY_MOTION.draw });
    expect(scheduleLine(0, BODY_MOTION)).toEqual({ stagger: 0, duration: 0 });
  });
});

describe('penTimings', () => {
  it('gives a lone contour the whole drawing time', () => {
    expect(penTimings(1, 300, 400)).toEqual([{ delay: 300, duration: 400 }]);
  });

  it('draws contours one after another with a little overlap', () => {
    expect(penTimings(4, 0, 400)).toEqual([
      { delay: 0, duration: 140 },
      { delay: 100, duration: 140 },
      { delay: 200, duration: 140 },
      { delay: 300, duration: 140 },
    ]);
  });
});

describe('inkTiming', () => {
  it('starts filling once most contours are down', () => {
    expect(inkTiming(1000, 400)).toEqual({ delay: 1200, duration: 240 });
  });
});
