/**
 * Hand-drawn outlines for the empty-canvas hint. `hint-glyphs.json` is generated by
 * `pnpm hint:glyphs` (scripts/hint-glyphs.mjs) from the `canvas.hintTitle` / `canvas.hintBody`
 * copy of every dictionary, tracing Excalifont (Latin) and Xiaolai (CJK) — the same hand-drawn
 * pair Excalidraw renders with. Shipping outlines instead of the fonts keeps the CJK font's
 * megabytes out of the bundle and gives the pen animation the paths it needs.
 */
import data from './hint-glyphs.json';

export interface HintGlyph {
  /** Key into `HintGlyphData.glyphs`. */
  g: string;
  /** Pen position on the line, in em units (1000 per em). */
  x: number;
}

export interface HintLine {
  width: number;
  glyphs: HintGlyph[];
}

export interface HintFont {
  name: string;
  license: string;
  source: string;
}

export interface HintGlyphData {
  unitsPerEm: number;
  ascent: number;
  descent: number;
  fonts: Record<string, HintFont>;
  /** One SVG path per contour so the pen can draw them one after another. */
  glyphs: Record<string, string[]>;
  lines: Record<string, HintLine>;
}

export const HINT_GLYPHS: HintGlyphData = data;

export function hintLine(text: string): HintLine | null {
  return HINT_GLYPHS.lines[text] ?? null;
}

/**
 * How a line writes itself: every glyph takes `draw` ms; the stagger between glyph starts is
 * fitted so the whole line lasts about `total` ms, within the stagger bounds.
 */
export interface MotionProfile {
  draw: number;
  total: number;
  minStagger: number;
  maxStagger: number;
}

export const TITLE_MOTION: MotionProfile = {
  draw: 420,
  total: 1600,
  minStagger: 40,
  maxStagger: 150,
};
export const BODY_MOTION: MotionProfile = {
  draw: 260,
  total: 1200,
  minStagger: 15,
  maxStagger: 60,
};

export interface LineSchedule {
  stagger: number;
  duration: number;
}

export function scheduleLine(glyphCount: number, profile: MotionProfile): LineSchedule {
  if (glyphCount <= 0) return { stagger: 0, duration: 0 };
  if (glyphCount === 1) return { stagger: 0, duration: profile.draw };
  const fitted = Math.round((profile.total - profile.draw) / (glyphCount - 1));
  const stagger = Math.min(profile.maxStagger, Math.max(profile.minStagger, fitted));
  return { stagger, duration: (glyphCount - 1) * stagger + profile.draw };
}

export interface Timing {
  delay: number;
  duration: number;
}

/** Contours of one glyph are drawn in order, each overlapping the next a little. */
export function penTimings(contours: number, start: number, draw: number): Timing[] {
  const slot = draw / Math.max(1, contours);
  const duration = Math.round(Math.min(draw, slot * 1.4));
  return Array.from({ length: contours }, (_, index) => ({
    delay: Math.round(start + index * slot),
    duration,
  }));
}

/** The fill starts once most of the glyph's contours are down. */
export function inkTiming(start: number, draw: number): Timing {
  return { delay: Math.round(start + draw * 0.5), duration: Math.round(draw * 0.6) };
}
