packages:
  - apps/*
  - packages/*

autoInstallPeers: true
strictPeerDependencies: false

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
